name: macrm
version: 1.0.0.7
github: "satosystems/macrm"
license: BSD3
author: "Satoshi Ogata"
maintainer: "satosystems@gmail.com"
copyright: "(c) 2018 Satoshi Ogata"

extra-source-files:
  - .editorconfig
  - .gitignore
  - .travis.yml
  - ChangeLog.md
  - Makefile
  - README.md
  - hie.yaml
  - share/man/man1/macrm.1.md

# Metadata used when publishing your package
synopsis: Alternative rm command for macOS that remove files/dirs to the system
  trash
category: Program

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/satosystems/macrm#readme>

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  other-modules:
    - Paths_macrm
  dependencies:
    - MissingH
    - cmdargs
    - cond
    - directory
    - exceptions
    - githash
    - inline-c
    - process
    - text
    - time
    - unix

executables:
  macrm:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
      - -optP-Wno-nonportable-include-path
    dependencies:
      - macrm

tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
    dependencies:
      - MissingH
      - bytestring
      - directory
      - filepath
      - hspec
      - macr
      - main-tester
      - process
      - unix
      - uuid
