name: macrm
version: 1.0.0.5
github: "satosystems/macrm"
license: BSD3
author: "Satoshi Ogata"
maintainer: "satosystems@gmail.com"
copyright: "(c) 2018-2020 Satoshi Ogata"

extra-source-files:
  - .editorconfig
  - .gitignore
  - ChangeLog.md
  - Makefile
  - README.md
  - hie.yaml

# Metadata used when publishing your package
synopsis: Alternative rm command for macOS that remove files/dirs to the system
  trash
category: Program

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/satosystems/macrm#readme>

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  other-modules:
    - Paths_macrm
  dependencies:
    - MissingH             >= 1.4.3 && < 1.5
    - cmdargs              >= 0.10.20 && < 0.11
    - cond                 >= 0.4.1 && < 0.5
    - directory            >= 1.3.6 && < 1.4
    - exceptions           >= 0.10.4 && < 0.11
    - githash              >= 0.1.4 && < 0.2
    - inline-c             >= 0.9.1 && < 0.10
    - process              >= 1.6.9 && < 1.7
    - text                 >= 1.2.4 && < 1.3
    - time                 >= 1.9.3 && < 1.10
    - unix                 >= 2.7.2 && < 2.8

executables:
  macrm:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
      - -optP-Wno-nonportable-include-path
    dependencies:
      - macrm

tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
    dependencies:
      - MissingH             >= 1.4.3 && < 1.5
      - bytestring           >= 0.10.10 && < 0.11
      - directory            >= 1.3.6 && < 1.4
      - filepath             >= 1.4.2 && < 1.5
      - hspec                >= 2.7.4 && < 2.8
      - macrm
      - main-tester          >= 0.2.0 && < 0.3
      - process              >= 1.6.9 && < 1.7
      - unix                 >= 2.7.2 && < 2.8
      - uuid                 >= 1.3.13 && < 1.4
