name: macrm
version: 1.0.0.3
github: "satosystems/macrm"
license: BSD3
author: "Satoshi Ogata"
maintainer: "satosystems@gmail.com"
copyright: "(c) 2018-2020 Satoshi Ogata"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
synopsis: Alternative rm command for macOS that throws
  files/directories away to the system trash
category: Program

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/satosystems/macrm#readme>

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  other-modules:
    - Paths_macrm
  dependencies:
    - MissingH
    - cmdargs
    - cond
    - directory
    - exceptions
    - filepath
    - githash
    - inline-c
    - process
    - text
    - time
    - unix

executables:
  macrm:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
      - -Werror
      - -optP-Wno-nonportable-include-path
    dependencies:
      - macrm

tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
      - -Werror
    dependencies:
      - MissingH >= 1.4.3.0 && < 2
      - bytestring <= 0.10.10.1 && < 1
      - directory <= 1.3.6.0 && < 2
      - filepath <= 1.4.2.1 && < 2
      - hspec >= 2.7.4 && < 3
      - macrm
      - main-tester <= 0.2.0.1 && < 1
      - process <= 1.6.9.0 && < 2
      - unix <= 2.7.2.2 && < 3
      - uuid <= 1.3.13 && < 2
